export const ENCOURAGING_PHRASES = [
  "Keep your smile bright",
  "Looking good, feeling fresh",
  "Your future self thanks you",
  "Squeaky clean!",
  "Brushing like a pro",
  "Flawless flossing",
  "Sparkle and shine",
  "Healthy habits, healthy smile",
  "One brush at a time",
  "Plaque's worst enemy",
  "Protect that enamel!",
  "Keep the streak alive",
  "Minty fresh!",
  "A smile a day keeps the dentist away",
  "You're doing great!",
  "Shining brighter every day",
  "Consistency is key",
  "Champion of oral hygiene",
  "Small habits, big results",
  "Tooth be told, you're awesome",
  "Keep up the great work",
  "Fresh breath, clear mind",
  "Your smile is your best accessory",
  "Defending against cavities!",
  "Building a lifetime smile",
  "Great job today!",
  "Keep glowing",
  "Another day, another brush",
  "Making your dentist proud",
  "You've got this!"
];
